version: "3.3"
services:
  postgresql:
    image: postgres:9.6
    container_name: mypostgresql1
    ports:
      - "5433:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgress
    tmpfs:
      - /tmp
      - /run/postgresql
    volumes:
      - ./docker_data/postgresql/data:/var/lib/postgresql/data/pgdata
      #- ./docker_build/postgresql/init.d:/docker-entrypoint-initdb.d
      - ./dbschema.sql:/docker-entrypoint-initdb.d/dbschema.sql
    restart: always
    networks:
      test_network:
         ipv4_address: 176.21.2.2
  redis:
     image: redis:3.2
     container_name: myredis1
     ports:
       - "6382:6379"
     volumes:
       - ./docker_data/redis/data:/data
     restart: always
     command: redis-server
     networks:
      test_network:
         ipv4_address: 176.21.2.1
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./docker_data/jenkins:/var/jenkins_home
      - ./docker_data/docker.sock:/var/run/docker.sock
    networks:
      test_network:
        ipv4_address: 176.21.2.3
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      test_network:
        ipv4_address: 176.21.2.4
  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://176.21.2.5:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      test_network:
        ipv4_address: 176.21.2.5
networks:
  test_network:
    driver: bridge
    ipam:
      config:
        - subnet: 176.21.2.0/16